### ISSUE TITLE
Converting recent Roll20 module consistently fails with error log?

### ISSUE THREAD

**Issue by derero97** [kakaroto/R20Exporter#26]
Hey, stupid question and I really REALLY hope this is the right place to ask it -I'm terribly sorry if not. I tried converting a bought module from Roll20 recently after subscribing to your Patreon, but the conversion consistently fails, both with the JSON version and the .zip. It just gives me the following error log: 

Error converting campaign : 
Traceback (most recent call last):
  File "src\GUI.py", line 183, in startConversion
  File "src\R20Converter.py", line 142, in convert
  File "src\entities\scenes.py", line 20, in __init__
  File "src\entities\scenes.py", line 31, in genEntities
  File "src\entities\scenes.py", line 31, in <listcomp>
  File "src\entities\scenes.py", line 286, in __init__
TypeError: '>' not supported between instances of 'str' and 'int'

Please contact the author with the log of the error from the console window

Did I fuck up somehow or does it have to do with the module being a recent release?

**Comment by AntonyWilliam** [comment]
Having the same error, any luck? 
Error converting campaign with R20Converter v0.11.2:
Traceback (most recent call last):

File "src\GUI.py", line 183, in startConversion
File "src\R20Converter.py", line 219, in convert
File "src\entities\actors.py", line 16, in __init__
File "src\entities\actors.py", line 19, in genEntities
File "src\entities\actors.py", line 19, in
File "src\entities\actors.py", line 495, in __init__
File "src\entities\actors.py", line 2175, in addActions
File "src\entities\actors.py", line 2110, in addPCAction
KeyError: 'data'

**Comment by kakaroto** [comment]
It's not the same error. And you're using 0.11.2. The latest version is 0.11.8. You're using Foundry v10 installed, while using an older release of the converter which didn't support Foundry v10. Update to the latest version of the converter (or downgrade to Foundry v9 to do the conversion before upgrading again)

**Comment by AntonyWilliam** [comment]
> 

Oh dang it, alright, i was using for a time and was working, time to go back to the patreon, thanks boss ✌🏻
