### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DLanier86** [kakaroto/R20Exporter#28]
I'm getting the following error when trying to convert a R20 campaign.

Error converting campaign with R20Converter v0.10.5:
Traceback (most recent call last):
File "src\GUI.py", line 183, in startConversion
File "src\R20Converter.py", line 154, in convert
File "C:\Users\kakaroto\AppData\Local\Programs\Python\Python38\lib\os.py", line 211, in makedirs
File "C:\Users\kakaroto\AppData\Local\Programs\Python\Python38\lib\os.py", line 211, in makedirs
File "C:\Users\kakaroto\AppData\Local\Programs\Python\Python38\lib\os.py", line 221, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:/Program Files/Foundry Virtual Tabletop/Data'

Please contact the author with the log of the error from the console window

**Comment by kakaroto** [comment]
You're pointing it to the folder where you installed Foundry instead of the folder where Foundry stores the game data. As the error says, "Access is denied" because no program should be allowed to write into `C:/Program Files` folder unless it runs as Administrator.
Check Foundry's setup page, it should have a place where it tells you what folder it's using for where it stores data (and it definitely shouldn't be in `C:/Program Files`). The converter should be able to auto-detect that path anyway, so don't modify it, let it us the default.

**Comment by DLanier86** [comment]
Thanks! I resolved by running as admin and then moved to a more appropriate folder.

It is running great! Thanks for the quick response.

Dave
