### ISSUE TITLE
Unable to finish conversion

### ISSUE THREAD

**Issue by koda-games** [kakaroto/R20Exporter#48]
Below is the error that i consistently get while trying to convert my world of Radiant Citadel. I cant seem to find a solution could i receive some help for this, Recent subscriber.

Error converting campaign with R20Converter v0.13.3:
Traceback (most recent call last):
File "src\GUI.py", line 183, in startConversion
File "src\R20Converter.py", line 223, in convert
File "src\entities\scenes.py", line 21, in __init__
File "src\entities\scenes.py", line 32, in genEntities
File "src\entities\scenes.py", line 32, in
File "src\entities\scenes.py", line 630, in __init__
KeyError: 'showlighting'

Please contact the author with the log of the error from the console window

**Comment by kakaroto** [comment]
Hi,
That's an error from R20Converter, not R20Exporter, so you filed in the wrong repo.
Regardless, the error is because you have a Jumpgate campaign, which R20Converter does not support. Only normal Roll20 campaigns can be converted with the tool at this time..
